config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"
  
  ## The routes are related to the URL
  ## resources :articles -> create all routes for 'articles'
  ## This is a short hand
  ## REST - Representational state transfer - mapping HTTP verbs (get, post, put/patch, delete)
  ## to CRUD actions
  resources :articles
  ## Use 'only:' to limit the generated routes
  ##resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]

  get "signup", to: "users#new"
  ## post "users", to: "user#create"

  ## This creates all the CRUD operations, except new because it has already been defined
  resources :users, except: [:new]

  # .../login
  get "login", to: "sessions#new"

  # Create request
  post "login", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  ## --- Category
  resources :categories, except: [:destroy]
  
end

app/models/article.rb
## '<' is to inherit from
class Article < ApplicationRecord
  ## Article only has 1 associated user
  belongs_to :user
  has_many :article_categories
  has_many :categories, through: :article_categories
  ## Active Record validation
  ## 'presence: true' - Forces the data to be NOT NULL
  ## 'length: {...}'  - Forces min/max string length
  validates :title, presence: true, length: { minimum: 6, maximum: 100 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  ## Peform this before any methods
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  ## Ensure user is logged in
  before_action :require_user, except: [:show, :index]

  ## Ensure user is current session user
  before_action :require_same_user, only: [:edit, :update, :destroy]
  
  def show
    ## 'params' is the data from the URL
    ## '@' denotes an instance variable
    ## user debugger to add a break point and start debuging
    #@article = Article.find(params[:id])
  end

  def index
    @articles = Article.paginate(page: params[:page], per_page: 3)
  end

  def new
    @article = Article.new
  end

  def create
    ## This can be used for debugging purposes
    ##render plain: params[:article]

    ## Using 'require' and 'permit' are security features
    @article = Article.new(article_params)
    @article.user = current_user
    
    if @article.save
      #render plain: @article.inspect

      ## notice OR alert
      flash[:notice] = "Article was created successfully!"

      ## Redirect to the newly created article page

      ## Short-hand
      ## redirect_to articles_path @article
      ## redirect_to articles_path #article_path(@article)
      
      redirect_to articles_path
    else
      ## Article save failed, re-render the 'new' page
      render "new"
    end
  end

  def edit
    #@article = Article.find(params[:id])

    # if @article.save
    #   flash[:notice] = "Article was created successfully!"
    #   redirect_to articles_path
    # else
    #   render "edit"
    # end
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article was updated successfully!"
      #redirect_to @article
      redirect_to articles_path
    else
      render "edit"
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  ## Only available to this controller below
  private
  
  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    ## .require is used to check if the top level key is present in params,
    ## if key is not present .require throws an error

    ## .permit method is used to specify the list of allowed or 
    ## permitted attributes for a given parameter.Any attributes 
    ## not explicitly permitted will be filtered out, providing 
    ## an additional layer of security
    ## Notice the 'category_ids' is an array
    params.require(:article).permit(:title, :description, category_ids: [])
  end

  def require_same_user
    ## 'current_user' is the user logged in
    ## '@article.user' is the user set by the server
    if !current_user.admin? && current_user != @article.user
      flash[:alert] = "You can only edit of delete your own article!"
      redirect_to @article #article_path
    end
  end

end

app/views/articles/_article.html.erb
<div class="row justify-content-md-center">
  <div class="col-8 mt-4">
    <div class="card text-center shadow">
      <div class="card-header fst-italic">
        by <%= link_to article.user.username, user_path(article.user) %>
        <% if article.categories.any? %>
          <div class= "mt-2">
            <%= render article.categories %>
            <%# @article.categories.each do |c| %>
              <%#= c.name %>
            <%# end %>
          </div>
        <% end %>
      </div>
      <div class="card-body">
        <% if header %>
          <h5 class="card-title">
            <%= link_to article.title, article_path(article), class: "text-success" %>
          </h5>
        <% end %>

        <% if trunc_body %>
          <p class="card-text text-start"><%= truncate(article.description, length: 100) %></p>
        <% else %>
          <div class="card-text text-start"><%= simple_format(article.description) %></div>
        <% end %>

        <% if article.user == current_user || (logged_in? && current_user.admin?) %>
          <%= link_to "Edit", edit_article_path(article), method: :edit, class: "btn btn-info" %>
          <%= link_to "Delete", article_path(article), class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
        <% end %>
      </div>
      <div class="card-footer text-body-secondary">
        <small>Created <%= time_ago_in_words(article.created_at) %> ago, 
        Edited <%= time_ago_in_words(article.updated_at) %> ago</small>
      </div>
    </div>
  </div>
</div>

app/views/articles/_form.html.erb
<div class="container">

  <%= render "shared/errors", obj: @article %>

  <%= form_with( model: @article, class: "shadow p-3 mb-3 bg-info-subtle rounded", local: true, data: { turbo: false } ) do |f| %>

    <div class="form-group row">
      <%= f.label :title, class: "col-2 col-form-label" %>
      <div class="col-10">
        <%= f.text_field :title, class: "form-control shadow", placeholder: "Title of Article" %>
      </div>
    </div>

    <div class="form-group row mb-2">
      <%= f.label :description, class: "col-2 col-form-label" %>
      <div class="col-10">
        <%= f.text_area :description, rows: 8, class: "form-control shadow", placeholder: "Description of Article" %>
      </div>
    </div>

    <div class="form-group row">
      <%= f.label :category, class: "col-2 col-form-label" %>
      <div class="col-10">
        <%# f.collection_select(:selector_ids, Object.all, :select_id, :select_name, options = {}, html_option = {}%>
        <%= f.collection_select(:category_ids, Category.all, :id, :name, 
                                {prompt: "Choose multiple categories, or none"}, 
                                {class: "form-select shadow", multiple: true, size: 5}) %>
      </div>
    </div>

    <div class="form-group row m-4 justify-content-center">
      <%= f.submit class: "btn btn-info col-3 shadow-sm" %>
    </div>

  <% end %>

  <%= link_to "[ Cancel and return to Article listing ]", articles_path, class: "text-info" %>
</div>

app/views/articles/edit.html.erb
<h1 class="m-4">Edit an Article</h1>

<% ## Check for errors %>
<%= render "form" %>

app/views/articles/index.html.erb
<h1 class= "m-4">All articles</h1>

<div class="m-4">
  <%= will_paginate @articles %>
</div>

<div class="container">

  <% @articles.each do |a| %>

    <%= render "article", article: a, header: true, trunc_body: true%>

  <% end %>
</div>

<div class="m-4">
  <%= will_paginate @articles %>
</div>

app/views/articles/new.html.erb
<h1 class= "m-4">Create a new Article</h1>

<% ## Check for errors %>
<%= render "form" %>


app/views/articles/show.html.erb
<h2 class= "m-4"><%= @article.title %></h1>

<div class="container">
  <%= render "article", article: @article, header: false, trunc_body: false %>
</div>