config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"
  
  ## The routes are related to the URL
  ## resources :articles -> create all routes for 'articles'
  ## This is a short hand
  ## REST - Representational state transfer - mapping HTTP verbs (get, post, put/patch, delete)
  ## to CRUD actions
  resources :articles
  ## Use 'only:' to limit the generated routes
  ##resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]

  get "signup", to: "users#new"
  ## post "users", to: "user#create"

  ## This creates all the CRUD operations, except new because it has already been defined
  resources :users, except: [:new]

  # .../login
  get "login", to: "sessions#new"

  # Create request
  post "login", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  ## --- Category
  resources :categories, except: [:destroy]
  
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :article_categories
  has_many :articles, through: :article_categories

  validates :name, presence: true, length: {minimum: 3, maximum: 25}
  validates_uniqueness_of :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_action :require_admin, except: [:index, :show]
  before_action :set_category, only: [:show, :edit, :update]

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created!"
      redirect_to @category ## Show page
    else
      render "new"
    end
  end

  def index
    @categories = Category.paginate(page: params[:page], per_page: 3)
  end

  def show
    @category_articles = @category.articles.paginate(page: params[:page], per_page: 3)
  end

  def edit
    ## edit shows the view
  end

  def update
    ## update handles the edit
    if @category.update(category_params)
      flash[:notice] = "Category was updated!"
      redirect_to categories_path
    else
      render "edit"
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  ## This ensures that the params object contains a key called "category".
  ## If it doesn’t, Rails will raise an ActionController::ParameterMissing error.
  ## This whitelists only the :name attribute inside the category parameters.
  ## Anything else (description, etc.) is discarded, so users can’t inject 
  ## unexpected data into your model.
  def category_params
    params.require(:category).permit(:name)
  end

  def require_admin
    if !(logged_in? && current_user.admin?)
      flash[:alert] = "You must be an admin user to perfom that action!"
      redirect_to categories_path
    end
  end

end

app/views/categories/_category.html.erb
<%# category is the default name generated by Rails when using the 'render' %>
<%#<span class="badge rounded-pill text-bg-info"> category.name </span> %>
<%= link_to category.name, category_path(category), class: "me-1 badge rounded-pill text-light text-bg-info" %>

app/views/categories/_form.html.erb
<%= form_with( model: @category, class: "shadow p-3 mb-3 bg-info-subtle rounded", 
              local: true, data: { turbo: false } ) do |f| %>

  <div class="form-group row mb-2">
    <%= f.label :name, "Category Name", class: "col-2 col-form-label" %>
    <div class="col-8">
      <%= f.text_field :name, class: "form-control shadow", 
                        placeholder: "Enter a category name" %>
    </div>
  </div>

  <div class="form-group row m-4 justify-content-center">
    <%= f.submit class: "btn btn-info col-3 shadow-sm" %>
  </div>

<% end %>

<%= link_to "[ Cancel and return to Category listing ]", categories_path, class: "text-info" %>

app/views/categories/edit.html.erb
<h1 class="m-4">Edit category name</h1>

<div class="container">

  <%= render "shared/errors", obj: @category %>

  <%= render "form" %>
</div>

app/views/categories/index.html.erb
<h1 class="m-4">Categories</h1>

<div class="m-4">
  <%= will_paginate @categories %>
</div>

<div class="container">
  <% @categories.each do |category| %>
    <div class="row justify-content-md-center">
      <div class="col-4 mt-2">
        <div class="card text-center shadow mb-4 bg-white rounded">
          <div class="card-body">
            <h5 class="card-title"><%= link_to category.name, category_path(category), class: "text-success" %></h5>
            <p class="card-text"><%= pluralize(category.articles.count, "article") %></p>
            <% if logged_in? && current_user.admin? %>
              <%= link_to "Edit", edit_category_path(category), method: :edit, class: "btn btn-info" %>
              <%#= link_to "Delete", article_path(article), class: "btn btn-danger", data: { turbo_method: :delete, turbo_confirm: "Are you sure?" } %>
            <% end %>
          </div>
          <div class="card-footer text-muted">
            <small>Created <%= time_ago_in_words(category.created_at) %> ago, 
            edited <%= time_ago_in_words(category.updated_at) %> ago</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<div class="m-4">
  <%= will_paginate @categories %>
</div>

app/views/categories/new.html.erb
<h1 class="m-4">Create a category</h1>

<div class="container">

  <%= render "shared/errors", obj: @category %>

  <%= render "form" %>
</div>

app/views/categories/show.html.erb
<h1 class="m-4">Category: <%= @category.name %></h1>

<div class= "text-center mt-4">
  <% if logged_in? && current_user.admin? %>
    <%= link_to "Edit category", edit_category_path(@category), class: "btn btn-info" %>
  <% end %>
</div>

<div class="m-4">
  <%# Make sure that the paginated variable is the one that's used in the '.each' block %>
  <%= will_paginate @category_articles %>
</div>

<div class="container">
  <% @category_articles.each do |a| %>
    <%= render "articles/article", article: a, header: true, trunc_body: true%>
  <% end %>
</div>