config/routes.rb
Rails.application.routes.draw do
  root "pages#home"
  get "about", to: "pages#about"
  
  ## The routes are related to the URL
  ## resources :articles -> create all routes for 'articles'
  ## This is a short hand
  ## REST - Representational state transfer - mapping HTTP verbs (get, post, put/patch, delete)
  ## to CRUD actions
  resources :articles
  ## Use 'only:' to limit the generated routes
  ##resources :articles, only: [:show, :index, :new, :create, :edit, :update, :destroy]

  get "signup", to: "users#new"
  ## post "users", to: "user#create"

  ## This creates all the CRUD operations, except new because it has already been defined
  resources :users, except: [:new]

  # .../login
  get "login", to: "sessions#new"

  # Create request
  post "login", to: "sessions#create"

  delete "logout", to: "sessions#destroy"

  ## --- Category
  resources :categories, except: [:destroy]
  
end

app/views/layouts/_footer.html.erb
<footer class="bg-body-tertiary text-center text-lg-start fixed-bottom">
  <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.05);">
    © 2025 Copyright:
    <a class="text-body" href="#">yourwebsitehere</a>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% 
    alerts = { "alert" => "warning", "notice"=> "success"}
    alert_type = alerts[name]
  %>

  <div class="container col-6">
    <div class="alert alert-<%= alert_type %> alert-dismissible fade show" role="alert">
      <%= msg %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-brand text-uppercase fw-bold" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <% if logged_in? %>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              <%= "(Admin) " if current_user.admin? %>Profile [<%= current_user.username %>]
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "View profile", user_path(current_user), class: "nav-link" %></li>
              <li><%= link_to "Edit profile", edit_user_path(current_user), class: "nav-link" %></li>
              <li>
                <%= link_to "Delete profile", user_path(current_user), class: "nav-link text-danger", 
                            data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }
                %>
              </li>
            </ul>
            <li><%= link_to "Log Out", logout_path, class: "nav-link", data: { turbo_method: :delete } %></li>
          </li>
        <% else %>
          <li class="nav-item"><%= link_to "Log In", login_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Sign Up", signup_path, class: "nav-link" %></li>
        <% end %>

        <li class="nav-item">
          <%= link_to "Bloggers", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu">
            <% if logged_in? %>
              <li><%= link_to "Create new article", new_article_path, class: "dropdown-item" %></li>
            <% end %>
            <li><%= link_to "View articles", articles_path, class: "dropdown-item" %></li>
            <%# <li><hr class="dropdown-divider"></li> %>
            <%# <li><a class="dropdown-item" href="#">Something else here</a></li> %>
          </ul>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Categories
          </a>
          <ul class="dropdown-menu">
            <% if logged_in? && current_user.admin? %>
              <li><%= link_to "Create new category", new_category_path, class: "dropdown-item" %></li>
            <% end %>
            <li><%= link_to "View categories", categories_path, class: "dropdown-item" %></li>
          </ul>
        </li>
      </ul>

      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>

    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Alpha Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "/custom" %>
    <%= javascript_importmap_tags %>
  </head>

  <body style= "height: 1500px">

    <%= render "layouts/navigation" %>

    <%# Refers to a 'partial'. Notice the lack of '_' %>
    <%= render "layouts/messages" %>
    
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>

</html>

